# Generated by Django 4.2.25 on 2026-08-10 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='شماره تلفن واردشده معتبر نیست.', regex='^[0-9۰-۹+()\\-\\s]{7,30}$')])),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'name'],
                'indexes': [models.Index(fields=['is_active', 'city'], name='main_repres_is_acti_3cc318_idx')],
            },
        ),
    ]
