# Generated by Django 4.2.25 on 2026-08-13 09:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_seed_sample_representatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='شماره تلفن واردشده معتبر نیست.', regex='^[0-9۰-۹+()\\-\\s]{7,30}$')])),
                ('email', models.EmailField(max_length=254)),
                ('desired_position', models.CharField(max_length=160)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(60)])),
                ('message', models.TextField()),
                ('resume', models.FileField(blank=True, upload_to='hiring/resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx')), main.models.validate_resume_size])),
                ('is_reviewed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('subtitle', models.CharField(max_length=240)),
                ('short_description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, upload_to='services/main/')),
                ('header_image', models.ImageField(blank=True, upload_to='services/headers/')),
                ('catalog_file', models.FileField(blank=True, upload_to='services/catalogs/')),
                ('position', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('benefit', 'مزیت و قابلیت'), ('process', 'مرحله اجرا')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.service')),
            ],
            options={
                'ordering': ['kind', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.service')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'position'], name='main_servic_is_acti_2a7c70_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringrequest',
            index=models.Index(fields=['is_reviewed', '-created_at'], name='main_hiring_is_revi_6adb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceitem',
            index=models.Index(fields=['service', 'kind', 'position'], name='main_servic_service_82d287_idx'),
        ),
    ]
