# Generated by Django 4.2.25 on 2026-08-13 11:09

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_seed_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('excerpt', models.TextField(max_length=500)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/')),
                ('author_name', models.CharField(default='تیم تحقیق و توسعه شرکت وزنه', max_length=160)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_posts', models.ManyToManyField(blank=True, help_text='حداکثر سه مطلب مرتبط را انتخاب کنید.', related_name='related_to_posts', to='main.blogpost')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='main_blogpo_is_publ_972a71_idx'), models.Index(fields=['is_featured', '-published_at'], name='main_blogpo_is_feat_32507c_idx')],
            },
        ),
    ]
