# Generated by Django 4.2.25 on 2026-08-13 12:48

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_seed_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_name_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, db_index=True, max_length=220),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='productcapacity',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productgalleryimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='productsize',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='producttype',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, db_index=True, max_length=180),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='title_en',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='projectgalleryimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='representative',
            name='address_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='city_en',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='representative',
            name='name_en',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
