# Generated by Django 4.2.25 on 2026-08-15

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_load_catalogue_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='blog/covers/'),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='resume',
            field=models.FileField(blank=True, max_length=500, upload_to='hiring/resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx')), main.models.validate_resume_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_file',
            field=models.FileField(blank=True, max_length=500, upload_to='products/catalogs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='header_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='products/headers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='products/main/'),
        ),
        migrations.AlterField(
            model_name='productgalleryimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='projects/main/'),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='catalog_file',
            field=models.FileField(blank=True, max_length=500, upload_to='services/catalogs/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='header_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='services/headers/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='services/main/'),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='services/gallery/'),
        ),
    ]
