# Generated by Django 4.2.25 on 2026-08-15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_support_vercel_blob_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='catalogs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کاتالوگ',
                'verbose_name_plural': 'کاتالوگ',
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='catalog_file',
        ),
        migrations.RemoveField(
            model_name='service',
            name='catalog_file',
        ),
    ]
